"""empty message

Revision ID: 40016fc5a0fc
Revises: ca0e09486641
Create Date: 2023-01-31 22:29:38.717323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40016fc5a0fc'
down_revision = 'ca0e09486641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
