"""empty message

Revision ID: 59c641f655b1
Revises: 214ecbfd33df
Create Date: 2023-02-01 15:38:16.379068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c641f655b1'
down_revision = '214ecbfd33df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('character_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.drop_column('created_by')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('planet_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planet_created_by_fkey', 'user', ['created_by'], ['id'])
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_created_by_fkey', 'user', ['created_by'], ['id'])
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
