"""empty message

Revision ID: 6ebba8be43d7
Revises: dca6dc7c1047
Create Date: 2023-02-02 20:57:06.849308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebba8be43d7'
down_revision = 'dca6dc7c1047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MGLT', sa.String(length=120), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=120), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('hyperdrive_rating', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('starship_class', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=120), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=120), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('opening_crawl', sa.String(length=120), nullable=True),
    sa.Column('producer', sa.String(length=120), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_height', sa.Integer(), nullable=True),
    sa.Column('average_lifespan', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=120), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('eye_colors', sa.String(length=120), nullable=True),
    sa.Column('hair_colors', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('skin_colors', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species')
    op.drop_table('films')
    op.drop_table('Vehicles')
    op.drop_table('Starships')
    # ### end Alembic commands ###
