"""empty message

Revision ID: b230c8f93e41
Revises: 6ebba8be43d7
Create Date: 2023-02-03 18:42:16.499790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b230c8f93e41'
down_revision = '6ebba8be43d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MGLT', sa.String(length=120), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=120), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('hyperdrive_rating', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('starship_class', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=120), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('starship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Vehicles')
    op.drop_table('Starships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Starships',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Starships_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('MGLT', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('cargo_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('consumables', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('cost_in_credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('crew', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hyperdrive_rating', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('max_atmosphering_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('starship_class', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Starships_pkey')
    )
    op.create_table('Vehicles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Vehicles_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('cargo_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('consumables', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('cost_in_credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('crew', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('max_atmosphering_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_class', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Vehicles_pkey')
    )
    op.drop_table('favorites_vehicles')
    op.drop_table('favorites_starships')
    op.drop_table('favorites_species')
    op.drop_table('favorites_films')
    op.drop_table('vehicles')
    op.drop_table('starships')
    # ### end Alembic commands ###
