"""empty message

Revision ID: c7b56687373b
Revises: ae5df6fa43be
Create Date: 2023-02-01 19:27:02.908771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b56687373b'
down_revision = 'ae5df6fa43be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('character_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['homeworld_id'], ['id'])
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_homeworld_fkey', 'planet', ['homeworld'], ['id'])
        batch_op.drop_column('homeworld_id')

    # ### end Alembic commands ###
